--#############################################################################
-- ARQUIVO: contas.sql
-- GERAÇÃO DO ARQUIVO CONTAS.TXT PARA O SIMBA
-- PLACEHOLDERS:
--   {{NUMERO_BANCO}}      → Código da instituição
--   {{AGENCIA_CLIENTE}}   → Agência do cliente
--   {{CONTAS_CLIENTE}}    → Lista de contas solicitadas

SELECT
    '{{NUMERO_BANCO}}' AS NUMERO_BANCO,
    LEFT(C.AGENCIA::TEXT, 4) AS NUMERO_AGENCIA,
    C.CONTA AS NUMERO_CONTA,
    '1' AS TIPO_CONTA,
    TO_CHAR(C.DATA_GERACAO, 'DDMMYYYY') AS DATA_ABERTURA_CONTA,
    CASE 
        WHEN COALESCE(M.DATA_DEMISSAO, M.DATA_EXCLUSAO) IS NULL THEN '' 
        ELSE TO_CHAR(COALESCE(M.DATA_DEMISSAO, M.DATA_EXCLUSAO), 'DDMMYYYY')
    END AS DATA_ENCERRAMENTO_CONTA,
    '1' AS MOVIMENTACAO_CONTA
FROM PUBLIC.MATRICULAS M
JOIN PUBLIC.CONTAS_CORRENTES C ON C.PESSOA = M.PESSOA_ID
WHERE C.AGENCIA = {{AGENCIA_CLIENTE}}
  AND C.CONTA IN ({{CONTAS_CLIENTE}});
