--#############################################################################
-- ARQUIVO: extrato.sql
-- GERAÇÃO DO ARQUIVO EXTRATO.TXT PARA O SIMBA
-- PLACEHOLDERS:
--   {{NUMERO_BANCO}}, {{AGENCIA_CLIENTE}}, {{CONTAS_CLIENTE}}, {{DATA_INICIAL}}, {{DATA_FINAL}}

DROP TABLE IF EXISTS PUBLIC.extrato_simba_3611_1;
select * into
public.extrato_simba_3611_1
from (

SELECT
rpad(CODIGO_CHAVE_EXTRATO::TEXT,18) as CODIGO_CHAVE_EXTRATO,
'{{NUMERO_BANCO}}',
left(NUMERO_AGENCIA::text,4) as NUMERO_AGENCIA,
NUMERO_CONTA,
TIPO_CONTA,
DATA_LANCAMENTO,
rpad(NUMERO_DOCUMENTO::text,5) as NUMERO_DOCUMENTO,
rpad(DESCRICAO_LANCAMENTO,40) as DESCRICAO_LANCAMENTO,
TIPO_LANCAMENTO,
RPAD(VALOR_LANCAMENTO::TEXT,14) AS VALOR_LANCAMENTO,
NATUREZA_LANCAMENTO,
VALOR_SALDO,
NATUREZA_SALDO,
LOCAL_TRANSACAO,
sequencia_ajj,
registroid
FROM (

SELECT 
*,
	replace(round(abs(SALDO),2)::text,'.','') AS VALOR_SALDO,
	(CASE WHEN SALDO < 0 THEN 'D' WHEN SALDO > 0 THEN 'C' ELSE 'C' END ) AS NATUREZA_SALDO



FROM (

SELECT *,
(SUM(VLRMOV_NAOVAI) OVER (ORDER BY ORDEM_NAOVAI)) AS SALDO

FROM (

SELECT
	cast(mocc.ctasoc as text)|| cast(mocc.id as text) AS CODIGO_CHAVE_EXTRATO,
	'{{NUMERO_BANCO}}' AS NUMERO_BANCO, 
	CODAGE AS NUMERO_AGENCIA,
	CTASOC AS NUMERO_CONTA,
	$$1$$ AS TIPO_CONTA, 
	format(DATMOV, 'ddmmyyyy') AS DATA_LANCAMENTO,
	CODHIS AS NUMERO_DOCUMENTO,
	(SELECT DESHIS FROM {{SCHEMA}}.HIST WHERE HIST.CODHIS = MOCC.CODHIS) AS DESCRICAO_LANCAMENTO,
	(CASE WHEN (CASE WHEN VLRMOV < 0.00 THEN 'D' WHEN VLRMOV >= 0.00 THEN 'C' ELSE 'C' END) = 'C' 
THEN
			CASE	WHEN CODHIS IN(0) THEN 201
	 			WHEN CODHIS IN(0) THEN 202
				WHEN CODHIS IN(0) THEN 203
				WHEN CODHIS IN (0) THEN 204
				WHEN CODHIS IN(0) THEN 206
				WHEN CODHIS IN(0) THEN 207
				WHEN CODHIS IN(22501,22504,22545,22521, 11517) THEN 209
				WHEN CODHIS IN(0) THEN 211
				WHEN CODHIS IN(22598,22597,42,43) AND VLRMOV >= 0 THEN 213
	 			WHEN CODHIS IN(0) THEN 217
				WHEN CODHIS IN(0) THEN 218
				WHEN CODHIS IN(0) THEN 219
				WHEN CODHIS IN(45) THEN 220
				WHEN CODHIS IN(0) THEN 221
				WHEN CODHIS IN(0) THEN 222
				WHEN CODHIS IN(0) THEN 223
			END	
				
		ELSE
			CASE	WHEN CODHIS IN(0) THEN 101
				WHEN CODHIS IN(0) THEN 102
				WHEN CODHIS IN(0) THEN 103
				WHEN CODHIS IN(22544,62,11524,22600) THEN 105
				WHEN CODHIS IN(0) THEN 106
				WHEN CODHIS IN(80) THEN 107
				WHEN CODHIS IN(0) THEN 109
				WHEN CODHIS IN(0) THEN 110
				WHEN CODHIS IN(0) THEN 112
	 			WHEN CODHIS IN(0) THEN 113
				WHEN CODHIS IN(0) THEN 114
				WHEN CODHIS IN(42,22597,22599,43,1326,842) AND VLRMOV < 0 THEN 117
				WHEN CODHIS IN(0) THEN 119
				WHEN CODHIS IN(22500, 11516) THEN 120
				WHEN CODHIS IN(0) THEN 121
				WHEN CODHIS IN(0) THEN 122
				WHEN CODHIS IN(0) THEN 123
				WHEN CODHIS IN(0) THEN 124
				WHEN CODHIS IN(11500) THEN 125
				WHEN CODHIS IN(0) THEN 126
				WHEN CODHIS IN(0) THEN 127			
			END
		END)::text AS TIPO_LANCAMENTO, 
	replace(round(abs(VLRMOV),2)::text,'.','') AS VALOR_LANCAMENTO,
	(CASE WHEN VLRMOV < 0.00 THEN 'D' WHEN VLRMOV >= 0.00 THEN 'C' ELSE 'D' END ) AS NATUREZA_LANCAMENTO,
	(RANK()OVER (ORDER BY DATMOV, SEQREG))AS ORDEM_NAOVAI,
	'AGÊNCIA' AS LOCAL_TRANSACAO
	,ROUND(vlrmov,2) AS VLRMOV_NAOVAI,
	mocc.seqreg as sequencia_ajj,
	mocc.registroid
FROM {{SCHEMA}}.MOCC 
WHERE CODAGE = {{AGENCIA_CLIENTE}} AND CTASOC IN ({{CONTAS_CLIENTE}}) and
DATMOV BETWEEN '{{DATA_INICIAL}}' AND '{{DATA_FINAL}}'
ORDER BY ctasoc,DATMOV,seqreg 
) AS A
) AS B
)AS C  order by numero_conta 
--where tipo_lancamento is null;
) AS D;


DROP TABLE IF EXISTS PUBLIC.extrato_simba_3611_1;
select * into
PUBLIC.extrato_simba_3611_1
from (

SELECT
rpad(CODIGO_CHAVE_EXTRATO::TEXT,18) as CODIGO_CHAVE_EXTRATO,
NUMERO_BANCO,
left(NUMERO_AGENCIA::text,4) as NUMERO_AGENCIA,
NUMERO_CONTA,
TIPO_CONTA,
DATA_LANCAMENTO,
rpad(NUMERO_DOCUMENTO::text,5) as NUMERO_DOCUMENTO,
rpad(DESCRICAO_LANCAMENTO,40) as DESCRICAO_LANCAMENTO,
TIPO_LANCAMENTO,
RPAD(VALOR_LANCAMENTO::TEXT,14) AS VALOR_LANCAMENTO,
NATUREZA_LANCAMENTO,
VALOR_SALDO,
NATUREZA_SALDO,
LOCAL_TRANSACAO,
sequencia_ajj,
registroid
FROM (

SELECT 
*,
	replace(round(abs(SALDO),2)::text,'.','') AS VALOR_SALDO,
	(CASE WHEN SALDO < 0 THEN 'D' WHEN SALDO > 0 THEN 'C' ELSE 'C' END ) AS NATUREZA_SALDO



FROM (

SELECT *,
(SUM(VLRMOV_NAOVAI) OVER (ORDER BY ORDEM_NAOVAI)) AS SALDO

FROM (

SELECT
	cast(mocc.ctasoc as text) || cast (mocc.id as text) AS CODIGO_CHAVE_EXTRATO,
	'{{NUMERO_BANCO}}' AS NUMERO_BANCO, 
	CODAGE AS NUMERO_AGENCIA,
	CTASOC AS NUMERO_CONTA,
	$$1$$ AS TIPO_CONTA, 
	format(DATMOV, 'ddmmyyyy') AS DATA_LANCAMENTO,
	CODHIS AS NUMERO_DOCUMENTO,
	(SELECT DESHIS FROM {{SCHEMA}}.HIST WHERE HIST.CODHIS = MOCC.CODHIS) AS DESCRICAO_LANCAMENTO,
	(CASE WHEN (CASE WHEN VLRMOV < 0 THEN 'D' WHEN VLRMOV > 0 THEN 'C' ELSE '*' END) = 'C' 
		THEN
			CASE	WHEN CODHIS IN(0) THEN 201
	 			WHEN CODHIS IN(0) THEN 202
				WHEN CODHIS IN(0) THEN 203
				WHEN CODHIS IN (0) THEN 204
				WHEN CODHIS IN(0) THEN 206
				WHEN CODHIS IN(0) THEN 207
				WHEN CODHIS IN(22501,22504,22545,22521, 11517) THEN 209
				WHEN CODHIS IN(0) THEN 211
				WHEN CODHIS IN(22598,22597,42,43) AND VLRMOV >= 0 THEN 213
	 			WHEN CODHIS IN(0) THEN 217
				WHEN CODHIS IN(0) THEN 218
				WHEN CODHIS IN(0) THEN 219
				WHEN CODHIS IN(45) THEN 220
				WHEN CODHIS IN(0) THEN 221
				WHEN CODHIS IN(0) THEN 222
				WHEN CODHIS IN(0) THEN 223
			END	
				
		ELSE
			CASE	WHEN CODHIS IN(0) THEN 101
				WHEN CODHIS IN(0) THEN 102
				WHEN CODHIS IN(0) THEN 103
				WHEN CODHIS IN(22544,62,11524,22600) THEN 105
				WHEN CODHIS IN(0) THEN 106
				WHEN CODHIS IN(80) THEN 107
				WHEN CODHIS IN(0) THEN 109
				WHEN CODHIS IN(0) THEN 110
				WHEN CODHIS IN(0) THEN 112
	 			WHEN CODHIS IN(0) THEN 113
				WHEN CODHIS IN(0) THEN 114
				WHEN CODHIS IN(42,22597,22599,43,1326,842) AND VLRMOV < 0 THEN 117
				WHEN CODHIS IN(0) THEN 119
				WHEN CODHIS IN(22500, 11516) THEN 120
				WHEN CODHIS IN(0) THEN 121
				WHEN CODHIS IN(0) THEN 122
				WHEN CODHIS IN(0) THEN 123
				WHEN CODHIS IN(0) THEN 124
				WHEN CODHIS IN(11500) THEN 125
				WHEN CODHIS IN(0) THEN 126
				WHEN CODHIS IN(0) THEN 127			
			END
		END)::text AS TIPO_LANCAMENTO, 
	replace(round(abs(VLRMOV),2)::text,'.','') AS VALOR_LANCAMENTO,
	(CASE WHEN VLRMOV < 0.00 THEN 'D' WHEN VLRMOV >= 0.00 THEN 'C' ELSE 'D' END ) AS NATUREZA_LANCAMENTO,
	(RANK()OVER (ORDER BY DATMOV, SEQREG))AS ORDEM_NAOVAI,
	'AGÊNCIA' AS LOCAL_TRANSACAO
	,ROUND(vlrmov,2) AS VLRMOV_NAOVAI,
	mocc.seqreg as sequencia_ajj,
	mocc.registroid
FROM {{SCHEMA}}.MOCC 
WHERE CODAGE = {{AGENCIA_CLIENTE}} AND CTASOC IN ({{CONTAS_CLIENTE}}) and
DATMOV BETWEEN '{{DATA_INICIAL}}' AND '{{DATA_FINAL}}' 
ORDER BY ctasoc,DATMOV,seqreg 
) AS A
) AS B
)AS C  order by numero_conta 
--where tipo_lancamento is null;
) AS D;

--criar uma sequencia para ser usada no campo  CODIGO_CHAVE_EXTRATO
ALTER TABLE PUBLIC.extrato_simba_3611_1 add column chave serial;

select * from PUBLIC.extrato_simba_3611_1;  

select CODIGO_CHAVE_EXTRATO,
       NUMERO_BANCO,
       NUMERO_AGENCIA,
       NUMERO_CONTA,
	   TIPO_CONTA,	
	   DATA_LANCAMENTO,
	   NUMERO_DOCUMENTO,
	   DESCRICAO_LANCAMENTO,
	   coalesce(TIPO_LANCAMENTO::text,'204'), 
       VALOR_LANCAMENTO,
	   NATUREZA_LANCAMENTO,
	   VALOR_SALDO,
	   NATUREZA_SALDO,
 	   LOCAL_TRANSACAO
from PUBLIC.extrato_simba_3611_1;