--#############################################################################
-- ARQUIVO: titulares.sql
-- GERAÇÃO DO ARQUIVO TITULARES.TXT PARA O SIMBA
-- PLACEHOLDERS:
--   {{NUMERO_BANCO}}, {{AGENCIA_CLIENTE}}, {{CONTAS_CLIENTE}}

SELECT
    '{{NUMERO_BANCO}}' AS NUMERO_BANCO,
    LEFT(SOCI.CODAGE::TEXT, 4) AS NUMERO_AGENCIA,
    SOCI.CTASOC AS NUMERO_CONTA,
    '1' AS TIPO_CONTA,
    'T' AS TIPO_TITULAR,
    '1' AS PESSOA_INVESTIGADA,
    CASE WHEN CHAR_LENGTH(CPFSOC) = 11 THEN '1' ELSE '2' END AS TIPO_PESSOA_TITULAR,
    CPFSOC AS CPF_CNPJ_TITULAR,
    REPLACE(REPLACE(REPLACE(REPLACE(SOCI.NOMSOC, E'\n', ' '), E'\r', ' '), '"', ''), '''', '') AS NOME_TITULAR,
    (SELECT DESTDO FROM {{SCHEMA}}.TDOC WHERE CODTDO = SOCI.CODTDO) AS NOME_DOC_IDENTIFICACAO,
    replace(replace(replace(replace((RGISOC || OEXSOC), '/',''), '.', ''), '-', ''), '"', '')  AS NUMERO_DOC_IDENTIFICACAO,
    ENDSOC AS ENDERECO_LOGRADOURO,
    (SELECT DESCRICAO FROM PUBLIC.MUNICIPIOS M WHERE M.CODIGO_IBGE = SOCI.CODMUN) AS ENDERECO_CIDADE,
    SIGEST AS ENDERECO_UF,
    'BRASIL' AS ENDERECO_PAIS,
    CEPSOC AS ENDERECO_CEP,
    COALESCE(FONSOC, FCESOC, (SELECT TELAGE FROM {{SCHEMA}}.AGEN WHERE AGEN.CODAGE = SOCI.CODAGE)) AS TELEFONE_PESSOA,
    ROUND(VRESOC, 2) AS VALOR_RENDA,
    TO_CHAR(DAPSOC, 'DDMMYYYY') AS DATA_ATUALIZACAO_RENDA,
    TO_CHAR(ADMSOC, 'DDMMYYYY') AS DATA_INICIO_RELACIONAMENTO_CONTA,
    TO_CHAR(CC.ENCERRAMENTO, 'DDMMYYYY') AS DATA_FIM_RELACIONAMENTO_CONTA
FROM {{SCHEMA}}.SOCI
JOIN PUBLIC.CONTAS_CORRENTES CC 
  ON CC.CONTA = SOCI.CTASOC
 AND CC.AGENCIA = SOCI.CODAGE
WHERE SOCI.CODAGE = {{AGENCIA_CLIENTE}}
  AND CTASOC IN ({{CONTAS_CLIENTE}})
ORDER BY CPFSOC, CTASOC DESC;
